server.port=9090

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/media_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Minio
minio.bucketname=media
minio.endpoint=http://localhost:9000
minio.accesskey=minioadmin
minio.secretkey=minioadmin

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.timeout=3000ms

# 视频处理工具
# ytdlp
tool.ytdlp.path=E:/Apps/yt-dlp/yt-dlp.exe
# ffmpeg
tool.ffmpeg.dir=E:/Apps/ffmpeg-8.0.1-essentials_build/bin

# AI api
ai.api-key=${DASHSCOPE_API_KEY:}

# vision model
ai.qwen.vision-model=qwen3-vl-flash
ai.qwen.base-url=https://dashscope.aliyuncs.com/compatible-mode/v1
ai.qwen.http-base-url=https://dashscope.aliyuncs.com/api/v1
ai.qwen.video-fps=2

# asr model
ai.asr.model=fun-asr-realtime
ai.asr.format=mp3
ai.asr.sample-rate=16000
ai.asr.websocket-url=wss://dashscope.aliyuncs.com/api-ws/v1/inference
ai.asr.http-base-url=https://dashscope.aliyuncs.com/api/v1
ai.asr.enable-itn=false

# RocketMQ
# 本机直接启动 Spring Boot 时，连宿主机映射端口
rocketmq.name-server=127.0.0.1:19876
# 生产者分组（建议显式配置）
rocketmq.producer.group=video-producer-group
rocketmq.producer.send-message-timeout=10000
rocketmq.producer.retry-times-when-send-failed=2

# Multipart upload limits
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2048MB
spring.servlet.multipart.max-request-size=2048MB
